npm i body-parser
npm i connect-redis
npm i cookie-parser
npm i express
npm i express-session
npm i morgan
npm i multer
npm i mysql
npm i nconf
npm i passport
npm i passport-local
npm i pug
npm i redis
